site_name: coaster.cloud
site_description: Dokumentation zur coaster.cloud App
site_url: https://docs.coaster.cloud
copyright: '&copy; 2021 ff. | Coaster.Cloud | <a href="#__consent">Change cookie settings</a>'
site_dir: /var/www/html/
dev_addr: 192.168.0.5:8000

theme:
  name: material
  language: de
  font: 
    text: Montserrat
  
  logo: assets/images/logos/logo_coaster_cloud_weiss.svg
  favicon: assets/images/logos/logo_coaster_cloud_square.png
  
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: indigo
      accent: yellow
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: deep purple
      accent: deep purple
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

  features:
    - announce.dismiss
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - search-suggest
    - search.highlight
    - search.share

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/coastercloudapp
      name: Twitter with us
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/coaster.cloud
      name: Lookup on Facebook
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/coaster.cloud/
      name: Stay in touch with Instagram

  homepage: /

  consent:
    title: Cookie consent
    description: >- 
      de: Ist das verrückt - wir lieben Kekse! Aber Deine Privatsphäre ist uns so wertvoll, dass diese Dokumentation ohne besondere Cookies auskommt.<br>
      en: It's crazy - we love cookies! But your privacy is so valuable to us that this documentary is without special cookies.
    actions:
      - accept

  alternate:
    - name: English
      link: ./en/ 
      lang: en
    - name: Deutsch
      link: ./de/
      lang: de

#Navigation
nav:
  - Start: index.md
  - Installieren: install/index.md
  - Einstellen: setup/index.md
  - Funktionen:
    - feature/index.md
  - Mitmachen:
    - contribute/index.md
    - Park: contribute/park.md
    - Attraktionen: contribute/attraction.md
    - Kategorien: contribute/categories.md
    - Aktivitäten: contribute/activities.md
  - Änderungen: changelog/index.md
  - Faq: 
    - faq/index.md
    - Fahrelemente: faq/elements.md
    - Rückhaltesystem: faq/restraint.md
  - Kontakt: contact/index.md

plugins:
  - search:
      lang:
        - de
        - en
  - i18n:
      default_language: de
      languages:
        en: 
          name: English
          site_name: coaster.cloud - Manual
        de: 
          name: Deutsch
          site_name: coaster.cloud - Handbuch
      nav_translations:
        de:
          Start: Start
          Installieren: Installation
          Einstellen: Einstellungen
          Funktionen: Funktionen
          Mitmachen: Mitmachen
          Park: Park
          Attraktionen: Attraktionen
          Kategorien: Kategorien
          Activities: Aktivitäten
          Änderungen: Änderungen
          Faq: FAQ
          Fahrlemente: Fahrelemente
          Rückhaltesystem: Rückhaltesystem
          Kontakt: Kontakt
        en:
          Start: Home
          Installieren: Install
          Einstellen: Setup
          Funktionen: Features
          Mitmachen: Contribute
          Park: Park
          Attraktionen: Attractions
          Kategorien: Categories
          Activities: Contributions
          Änderungen: Changes
          Faq: FAQ
          Fahrelemente: Ride Elements
          Rückhaltesystem: Restraint
          Kontakt: Contact

# Extensions
markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icon
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
